apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gps-backend:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@db:5432/gps_gis_db"